### ISSUE TITLE
Some problems still persist

### ISSUE THREAD

**Issue by newbiee12** [btiteam/xbtit#30]
I have just installed the 2.5.2 version and I still can't see anything that I'm typing in the paths for log name and log path. That happens when I use Firefox (48.0). I tested the same thing in IE and the cursor would not really move forward. It's weird, but I can type in the field where PHP error messages are supposed to show up.

Another thing, as seen on the screenshot, I'm not sure if it's only me, but there seems to be a problem with displaying language names during installation http://imgur.com/a/EzhuD

Lastly, I'm not sure if it was meant to be this way, but after installation was complete, some extra stuff seems to have been added to the tracker's urls in the Tracker's settings:

a:2:{i:0;s:30:"http://www.MYSITE.net/newtraktest/announce.php
";i:1;s:30:"http://www.MYSITE.net:2710/announce";}

Shouldn't it be just?

http://www.MYSITE.net/newtraktest/announce.php
http://www.MYSITE.net:2710/announce

----

If it helps, I can provide you with the full tracker address and login credentials. Just pm me or something if it's possible here.

Thanks!

**Comment by Gh0st4unt3r** [comment]
I have just noticed these aswell, the team are on it to try and resolve this for you and will have a closer look myself too, we will be making some file changes and release 2.5.3 to fix these issues.

**Comment by Gh0st4unt3r** [comment]
Update:  i found the announce will work its just adding some extra characters into the database which can be amended. i will see now where its pulling the extra information from in the source code.

**Comment by q8-hma** [comment]
language list fix and working on the log
for now u need to make log folder permission 777 or 755
and when u add the folder dont add / on the last

try this for now

**Comment by q8-hma** [comment]
Hello 
I need some info about ur server (OS - PHP version, Mysql version etc)
and where the log folder is in the xbtit home or no

thnx

**Comment by newbiee12** [comment]
Hi.
Here's the info
Linux 3.16.0-4-amd64 Debian 8.5
PHP 5.6.24
MySQL 5.5.50
The log folder is one directory above the website root. It's the same configuration I have for xbtit 2.4.0, which is working well.

**Comment by q8-hma** [comment]
try this one

open functions.php
find
````php
//create some logging :)
require_once($CURRENTPATH.'/conextra.php');
$signon= getConnection ();
$prefix=getPrefix ();
$logname=mysqli_fetch_row(mysqli_query($signon, "SELECT `value` FROM {$prefix}settings WHERE `key`='php_log_name' LIMIT 1"));
$logpath=mysqli_fetch_row(mysqli_query($signon, "SELECT `value` FROM {$prefix}settings WHERE `key`='php_log_path' LIMIT 1"));
$when=@date("d.m.y");
ini_set('log_errors','On'); // enable or disable php error logging (use 'On' or 'Off')

ini_set('error_log',$logpath[0].'/'.$logname[0].'_'.$when.'_.log'); // path to server-writable log file
```
replace with

````php
ini_set("log_errors", 'On'); // enable or disable php error logging (use 'On' or 'Off')
//create some logging :)
require_once($CURRENTPATH.'/conextra.php');
$signon= getConnection ();
$prefix=getPrefix ();
$logname=mysqli_fetch_row(mysqli_query($signon, "SELECT `value` FROM {$prefix}settings WHERE `key`='php_log_name' LIMIT 1"));
$logpath=mysqli_fetch_row(mysqli_query($signon, "SELECT `value` FROM {$prefix}settings WHERE `key`='php_log_path' LIMIT 1"));
$when=@date("d.m.y");
if(!is_dir($logpath[0].'/')){
mkdir($logpath[0], 0777, true);
file_put_contents($logpath[0].'/'.$logname[0].'_'.$when.'_.log',"");
ini_set('error_log',$logpath[0].'/'.$logname[0].'_'.$when.'_.log'); // path to server-writable log file
error_log(date('l jS \of F Y h:i:s A'));
}else
ini_set('error_log',$logpath[0].'/'.$logname[0].'_'.$when.'_.log'); // path to server-writable log file
```

**Comment by lord128** [comment]
I have the same issue on  2.5.2 version : critical issue at first step of install when trying to find the language path "/language/install_lang/". It seems the variable __DIR__ is one of the root cause. Compared to a working installation of xbtit 2.00 on the same server, the variable shall be replaced with "dirname(__FILE__) instead of "__DIR__". After the changes in the install.php script without issue, the main page is not displayed (no main screen).
Here is my config info (works fine with xbtit 2.00)
Windows 7 - 64
xampp 1.7.1
+ Apache 2.2.11
+ MySQL 5.1.33
+ PHP 5.2.9
+ SQLite 2.8.15
+ phpMyAdmin 3.1.3.1

**Comment by q8-hma** [comment]
Hello

u report about 3 problem
1-language list
2-log not view ... it's done or no ?
3-announce url ... it's done or no ?

can u upload new install.php on ur folder

because i try now the new now and i got the right list
http://i.imgur.com/rnE5acr.png

**Comment by lord128** [comment]
1st issue : http://hpics.li/a0e4a60
2nd issue : http://hpics.li/f3d4527 (no language list)
3 : new install php file , but failed at the end (see http://hpics.li/4fcaf4a)
[install_php.docx](https://github.com/btiteam/xbtit/files/435599/install_php.docx)

**Comment by q8-hma** [comment]
the problem because windows bro i will fix it to support windows

try it on linux and it will work fine

**Comment by lord128** [comment]
yes on my QNAP NAS server the installation script works perfectly !

**Comment by q8-hma** [comment]
Hello

try the new install.php I updated to work fine for windows and linux

tomorrow will update all files to work on windows server 

try and let me know

**Comment by lord128** [comment]
The issues are still there ..

**Comment by newbiee12** [comment]
I will test it later today and let you know asap. I was traveling all day yesterday.

**Comment by lord128** [comment]
No problem and no hurry !
It works fine on QNAP NAS

2016-08-25 13:46 GMT+02:00 newbiee12 <notifications@github.com>:

**Comment by lord128** [comment]
Hello !
I have installed a fresh version of UniServerZ at http://www.uniformserver.com/ for Windows
then the Visual C++ Redistributable for Visual Studio 2015.
Then I have installed the xbtit-XBTIT-2-DEV script installation and.. surprise.. all bugs went out ! Your changes have fixed all the previous bugs (misc. bugs on language and crash of the install script)

Thanks !

**Comment by q8-hma** [comment]
thnx lord128 
we waiting newbiee12 to see if it work fine with him 

we will working hard to find all the bugs and fix them as soon as we get them

**Comment by lord128** [comment]
thanks to YOU ! good job !

**Comment by newbiee12** [comment]
The language issue has been fixed.

Tracker's urls are displayed properly now

The PHP issues still persist on my tracker.

**Comment by q8-hma** [comment]
> The PHP issues still persist on my tracker
because xamapp and windows we will fix it on 2.5.3

or u can now replace all `__DIR__ `
with
`dirname(__FILE__)`
in index.php

**Comment by newbiee12** [comment]
There was only one occurence found in index.php

It didn't help.

**Comment by q8-hma** [comment]
I need u to make new php file ,add code and take screen shot

<?
print_r($_SERVER['DOCUMENT_ROOT']);
print_r(__DIR__);
print_r(dirname(__FILE__));

**Comment by newbiee12** [comment]
Where do you need me to place the file? In the tracker main directory or my website main directory?

**Comment by q8-hma** [comment]
tracker main dir

**Comment by newbiee12** [comment]
Shouldn't it be __DIR__, not __DIR_ ?

Here's the outcome of __DIR__

http://imgur.com/a/YO1M2

**Comment by q8-hma** [comment]
yes I forgot the last one

please edit it and take full pic

thnx

**Comment by newbiee12** [comment]
Here you go
http://imgur.com/a/Cy9IQ

**Comment by q8-hma** [comment]
Hello
try this code and give me screenshot
`<?
echo("1-".$SERVER['DOCUMENT_ROOT']);
echo("<br>2-".__DIR__);
echo("<br>3-".dirname(__FILE__));
echo("<br>______________<br>");
echo("1-".realpath($SERVER['DOCUMENT_ROOT']));
echo("<br>2-".realpath(__DIR__));
echo("<br>3-".realpath(dirname(__FILE__)));`

**Comment by newbiee12** [comment]
Here you go:

http://imgur.com/l3HRWHY

**Comment by q8-hma** [comment]
try this one
delete index.php and download
https://github.com/btiteam/xbtit/blob/XBTIT-2-DEV/index.php

**Comment by newbiee12** [comment]
Done. The outcome is the same as before, i.e. http://imgur.com/l3HRWHY

Also, I still can't see the things being typed in the PHP panel.

**Comment by q8-hma** [comment]
take screenshot when u open the tracker

**Comment by newbiee12** [comment]
http://imgur.com/a/TZ4wv

http://imgur.com/a/EJlGs

http://imgur.com/a/6fOyc

**Comment by q8-hma** [comment]
@newbiee12 .. bro now what the error ??

**Comment by newbiee12** [comment]
Looks like it.

**Comment by q8-hma** [comment]
log folder must be 755 and make and error test and see it work or no

**Comment by newbiee12** [comment]
The log folder has been set to 777 since the very beginning. I have changed it to 775, but it hasn't solved the issues.

There is quite a few of errors in apache2 error logs:

[Fri Aug 26 10:20:49.265209 2016] [:error] [pid 699] [client 208.102.116.64:53241] PHP Notice:  unserialize(): Error at offset 0 of 57 bytes in /home/www/smc/newtraktest/include/config.php on line 188, referer: http://www.MYSITE.net/newtraktest/index.php

[Fri Aug 26 10:03:22.572635 2016] [:error] [pid 694] [client 208.102.116.64:53187] PHP Notice:  Undefined variable: SERVER in /home/www/smc/newtraktest/testfile.php on line 6

[Thu Aug 25 16:13:21.228150 2016] [:error] [pid 27725] [client 208.102.116.64:51275] PHP Notice:  Use of undefined constant FILE - assumed 'FILE' in /home/www/smc/newtraktest/testfile.php on line 4

[Thu Aug 25 15:39:32.304377 2016] [:error] [pid 27591] [client 208.102.116.64:51097] PHP Notice:  Use of undefined constant __DIR_ - assumed '__DIR_' in /home/www/smc/newtraktest/testfile.php on line 3

This is the most common error in the logs:

[Thu Aug 25 15:24:46.434402 2016] [:error] [pid 27506] [client 208.102.116.64:51021] PHP Notice:  unserialize(): Error at offset 0 of 57 bytes in /home/www/smc/newtraktest/include/config.php on line 188, referer: http://www.MYSITE.net/newtraktest/index.php?page=admin&user=2&code=287585&do=php_log

**Comment by q8-hma** [comment]
issue of unserialize fixed

the log is server issue we will try fix it on 2.5.3

**Comment by newbiee12** [comment]
Ok. Thanks!

I wonder how come it's working properly in xbtit 2.4.0. That's what I'm using for my tracker. Were there any or serious changes in the code for xbtit 2.5.x compared to 2.4.0 that may be causing these problems?

**Comment by q8-hma** [comment]
ur welcome

not alot of change

if u need to change it manually
open .htaccess  
add this code
`
php_value log_errors 1
php_value error_log /path/to/php-error.log
`

**Comment by newbiee12** [comment]
You will never guess what's causing the problem. I'm not a CSS expert, but by analyzing the code and deleting parts of the script and testing the outcome I found out that the problem is in bootstrap.css that is in the style/xbtit-default/css folder.

If you delete this from bootstrap.css (it starts at line 1068):

```
* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```

I have no idea what it does, but it fixes the problem!

http://imgur.com/a/ZlyVe

**Comment by newbiee12** [comment]
I'm still getting the `PHP Notice:  unserialize(): Error at offset 0 of 39 bytes in... config.php on line 188` but it's 39 bytes now. It was 57 before.

**Comment by q8-hma** [comment]
Hello

i update files
include/config.php
admin/admin.config.php

u need to open tracker setting and update the files after that click save on tracker setting

**Comment by newbiee12** [comment]
It seems that it's fixed the problem. Thank you.

It's funny that when I removed the problematic lines from bootstrap.css and uploaded the modified file to the server, the fields username and password, create account and recover password were not visible on the main website. I had to reupload the unmodified bootstrap.css to be able to log in to the tracker, but as a result of that the problems in PHP Error Log reappeared.

Also, this message appears when you use "Optimize" in Database Utilities:

[27-Aug-2016 10:31:24 America/Denver] PHP Notice:  Array to string conversion in /home/www/smc/newtraktest/include/crk_protection.php on line 117

This message appears when you create a new one or modify an existing poll. Also, the poll title becomes "invisible" and you can't click on its title to modify it:

[27-Aug-2016 10:40:39 America/Denver] PHP Warning:  Invalid argument supplied for foreach() in /home/www/smc/newtraktest/admin/admin.polls.php on line 83

http://imgur.com/a/TnWvV

**Comment by q8-hma** [comment]
Hello
I will see the bug and i will fix them

thnx

**Comment by q8-hma** [comment]
polls is fixed

file "include/class.ajaxpoll.php" edited
file "style/xbtit_default/admin.polls.tpl" edited

u need to update ur file too

**Comment by newbiee12** [comment]
The title of the poll shows up now, but only for the polls created after you fixed the files. However, the "Move down" function for the poll's options is not working. Not sure if that's the case here, but after clicking "Save" the poll, the PHP log shows a similar thing as above for optimizing a database:

[27-Aug-2016 12:40:23 America/Denver] PHP Notice:  Array to string conversion in /home/www/smc/newtraktest/include/crk_protection.php on line 117

**Comment by q8-hma** [comment]
i will see it now and test it

**Comment by newbiee12** [comment]
Ok, cool.

**Comment by newbiee12** [comment]
Hi,

Are there any updates on the style issues related to bootstrap.css?

Also, I just updated to 2.5.3 and there is still an issue with the crk_protection file when managing the polls AND using the database utilities:

[30-Aug-2016 14:26:01 America/Denver] PHP Notice:  Array to string conversion in /home/www/smc/newtraktest/include/crk_protection.php on line 137

As for the polls, moving the options down is still not working.

Thanks!
